# Copyright (c) 2023 Centre Tecnologic de Telecomunicacions de Catalunya (CTTC)
#
# SPDX-License-Identifier: GPL-2.0-only

# NS3 CI script for CLANG

# Any scheduled pipeline for CLANG should define a variable, named
# "RELEASE", that has a value "weekly". Also, a variable "CLANG" should be set
# to True.

# We support CLANG >17
# The test is done under Linux.

.weekly-build-clang-ubuntu24.04:
  image: ubuntu:24.04
  extends: .base-build
  rules:
    - if: $RELEASE == "weekly"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
  before_script:
    - apt --quiet update
    - apt --quiet upgrade --yes
    - apt --quiet install --yes --no-install-recommends
      ca-certificates
      clang-$CLANG lld-$CLANG libc++-$CLANG-dev libc++abi-$CLANG-dev
      cmake ninja-build ccache build-essential
      libboost-all-dev
      libeigen3-dev
      libgsl-dev $LIBGSL gsl-bin
      libgtk-3-0 libgtk-3-dev
      libsqlite3-dev sqlite3
      libxml2 libxml2-dev
      python3 python3-dev
      ssh git
  variables:
    COMPILER: clang++-$CLANG
    LIBGSL: libgsl27

# CLANG 17
weekly-build-clang-17-debug:
  extends: .weekly-build-clang-ubuntu24.04
  variables:
    CLANG: 17
    MODE: debug

weekly-build-clang-17-default:
  extends: .weekly-build-clang-ubuntu24.04
  variables:
    CLANG: 17
    MODE: default

weekly-build-clang-17-optimized:
  extends: .weekly-build-clang-ubuntu24.04
  variables:
    CLANG: 17
    MODE: optimized

# CLANG rolling
.weekly-build-clang-ubuntu-rolling:
  image: ubuntu:rolling
  extends: .base-build
  tags: ["$TAG"]
  parallel:
    matrix:
      - TAG: ["CTTC", "arm64"]
  rules:
    - if: $RELEASE == "weekly"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
  before_script:
    - apt --quiet update
    - apt --quiet upgrade --yes
    - apt --quiet install --yes --no-install-recommends
      ca-certificates
      clang cmake ninja-build ccache build-essential
      git
      libboost-all-dev
      libeigen3-dev
      libgsl-dev $LIBGSL gsl-bin
      libgtk-3-0 libgtk-3-dev
      libsqlite3-dev sqlite3
      libxml2-16 libxml2-dev
      python3 python3-dev
      ssh
  variables:
    COMPILER: clang++
    LIBGSL: libgsl28

weekly-build-clang-rolling-debug:
  extends: .weekly-build-clang-ubuntu-rolling
  variables:
    MODE: debug

weekly-build-clang-rolling-default:
  extends: .weekly-build-clang-ubuntu-rolling
  variables:
    MODE: default

weekly-build-clang-rolling-optimized:
  extends: .weekly-build-clang-ubuntu-rolling
  variables:
    MODE: optimized
