# Copyright (c) 2023 Centre Tecnologic de Telecomunicacions de Catalunya (CTTC)
#
# SPDX-License-Identifier: GPL-2.0-only

# NS3 CI script for GCC

# Any scheduled pipeline for GCC should define a variable, named
# "RELEASE", that has a value "weekly". Also, a variable "GCC" should be set
# to True.

# We support from 10 to the latest version. Check if everything builds fine
# under debug, default, and optimized, on Linux.

.weekly-build-gcc-base:
  extends: .base-build
  rules:
    - if: $RELEASE == "weekly"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
  before_script:
    - apt update
    - apt upgrade --yes
    - DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends --yes
      ca-certificates
      $COMPILER ninja-build ccache
      python3 python3-dev python3-pip python3-venv
      build-essential git
      gsl-bin libgsl-dev $LIBGSL
      libboost-all-dev
      libc6-dev
      libgtk-3-dev
      libfl-dev
      libxml2 libxml2-dev
      libsqlite3-dev sqlite3
      libeigen3-dev
      ssh
    - python3 -m venv ns3env
    - source ./ns3env/bin/activate
    - pip install cmake==3.24.0

# GCC 11
weekly-build-gcc-11-debug:
  extends: .weekly-build-gcc-base
  image: ubuntu:22.04
  variables:
    MODE: debug
    COMPILER: g++-11
    LIBGSL: libgsl27

weekly-build-gcc-11-default:
  extends: .weekly-build-gcc-base
  image: ubuntu:22.04
  variables:
    MODE: default
    COMPILER: g++-11
    LIBGSL: libgsl27

weekly-build-gcc-11-optimized:
  extends: .weekly-build-gcc-base
  image: ubuntu:22.04
  variables:
    MODE: optimized
    COMPILER: g++-11
    LIBGSL: libgsl27

# GCC 12
weekly-build-gcc-12-debug:
  extends: .weekly-build-gcc-base
  image: ubuntu:22.04
  variables:
    MODE: debug
    COMPILER: g++-12
    LIBGSL: libgsl27

weekly-build-gcc-12-default:
  extends: .weekly-build-gcc-base
  image: ubuntu:22.04
  variables:
    MODE: default
    COMPILER: g++-12
    LIBGSL: libgsl27

weekly-build-gcc-12-optimized:
  extends: .weekly-build-gcc-base
  image: ubuntu:22.04
  variables:
    MODE: optimized
    COMPILER: g++-12
    LIBGSL: libgsl27

# GCC 13
weekly-build-gcc-13-debug:
  extends: .weekly-build-gcc-base
  image: ubuntu:24.04
  variables:
    MODE: debug
    COMPILER: g++-13
    LIBGSL: libgsl27

weekly-build-gcc-13-default:
  extends: .weekly-build-gcc-base
  image: ubuntu:24.04
  variables:
    MODE: default
    COMPILER: g++-13
    LIBGSL: libgsl27

weekly-build-gcc-13-optimized:
  extends: .weekly-build-gcc-base
  image: ubuntu:24.04
  variables:
    MODE: optimized
    COMPILER: g++-13
    LIBGSL: libgsl27

weekly-build-gcc-13-optimized-sanitizers:
  extends: .weekly-build-gcc-base
  image: ubuntu:24.04
  variables:
    MODE: optimized
    COMPILER: g++-13
    EXTRAS: --enable-sanitizers
  tags:
    - CTTC

weekly-build-gcc-13-optimized-noeigen:
  extends: .weekly-build-gcc-base
  image: ubuntu:24.04
  variables:
    MODE: optimized
    COMPILER: g++-13
    EXTRAS: --disable-eigen

# GCC rolling
.weekly-build-gcc-ubuntu-rolling:
  image: ubuntu:rolling
  extends: .base-build
  tags: ["$TAG"]
  parallel:
    matrix:
      - TAG: ["CTTC", "arm64"]
  rules:
    - if: $RELEASE == "weekly"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
  before_script:
    - apt --quiet update
    - apt --quiet upgrade --yes
    - apt --quiet install --yes --no-install-recommends
      ca-certificates
      g++ cmake ninja-build ccache build-essential
      git
      libboost-all-dev
      libeigen3-dev
      libgsl-dev $LIBGSL gsl-bin
      libgtk-3-0 libgtk-3-dev
      libsqlite3-dev sqlite3
      libxml2-16 libxml2-dev
      python3 python3-dev
      ssh
  variables:
    COMPILER: g++
    LIBGSL: libgsl28

weekly-build-gcc-rolling-debug:
  extends: .weekly-build-clang-ubuntu-rolling
  variables:
    MODE: debug

weekly-build-gcc-rolling-default:
  extends: .weekly-build-clang-ubuntu-rolling
  variables:
    MODE: default

weekly-build-gcc-rolling-optimized:
  extends: .weekly-build-gcc-ubuntu-rolling
  variables:
    MODE: optimized

weekly-regression-testing:
  image: ubuntu:rolling
  extends: .base-build
  tags:
    - CTTC
  rules:
    - if: $RELEASE == "weekly"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
  variables:
    MODE: optimized
    COMPILER: g++
    REGRESSION_TEST: "true"
  allow_failure: true
  timeout: 60h
  before_script:
    - apt --quiet update
    - apt --quiet upgrade --yes
    - apt --quiet install --yes --no-install-recommends
      ca-certificates
      g++ cmake ninja-build ccache build-essential
      git
      libboost-all-dev
      libeigen3-dev
      libgsl-dev $LIBGSL gsl-bin
      libgtk-3-0 libgtk-3-dev
      libsqlite3-dev sqlite3
      libxml2-16 libxml2-dev
      python3 python3-dev python3-scipy python3-psutil
      ssh
  artifacts:
    when: on_failure
    paths:
      - ns-3-dev/build/contrib/nr/examples/3gpp-outdoor-calibration
