# Copyright (c) 2023 Centre Tecnologic de Telecomunicacions de Catalunya (CTTC)
#
# SPDX-License-Identifier: GPL-2.0-only

# ns-3 CI/CD script with the code-linting stage
#
# Contains jobs to check the ns-3 coding style and perform lint checking.

# Clang-format
check-style-clang-format:
  stage: code-linting
  image: ubuntu:latest
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y
      python3
      clang-format-15
      git
  script:
    - git clone https://gitlab.com/nsnam/ns-3-dev.git
    - mkdir -p ns-3-dev/contrib/nr/
    - cp -r CMakeLists.txt  doc  tutorial examples  helper  model  README.md  RELEASE_NOTES.md  test  utils ns-3-dev/contrib/nr/
    - cd ns-3-dev
    - python3 utils/check-style-clang-format.py contrib/nr/model
    - python3 utils/check-style-clang-format.py contrib/nr/helper
    - python3 utils/check-style-clang-format.py contrib/nr/utils
    - python3 utils/check-style-clang-format.py contrib/nr/examples
    - python3 utils/check-style-clang-format.py contrib/nr/test
    - python3 utils/check-style-clang-format.py --no-formatting contrib/nr/doc
    - python3 utils/check-style-clang-format.py --no-formatting contrib/nr/tutorial
  timeout: 1h

# Check cmake format
cmake-format:
  stage: code-linting
  image: python:latest
  before_script:
    - pip install pyyaml cmake cmake-format ninja
  script:
    - git clone https://gitlab.com/nsnam/ns-3-dev.git
    - mkdir -p ns-3-dev/contrib/nr/
    - cp -r CMakeLists.txt  doc  tutorial examples  helper  model  README.md  RELEASE_NOTES.md  test  utils ns-3-dev/contrib/nr/
    - cd ns-3-dev
    - ./ns3 configure --enable-modules=core
    - ./ns3 build cmake-format-check
  timeout: 1h

# Check Python format
python-format:
  stage: code-linting
  image: python:latest
  before_script:
    - pip install black isort
  script:
    - black --check .
    - isort --check .
  timeout: 1h
